# Project-wide Gradle settings.
android.useAndroidX=true
# Since we are compiling a legacy app that might use hidden APIs and deprecated libraries,
# having androidX enabled is good, but wait, the decompiled code doesn't use AndroidX yet (it uses old android.app, android.support maybe).
# AndroidX transition might not even be strictly required unless we use modern libraries,
# but we can enable androidX anyway as it is standard now.
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
