DEBUG=false
CUSTOMER.NAME=HTC
HEAPSIZE=20971520
MENU.ROTATION.ENABLE=true
MENU.MOVE.DISABLE=false
MENU.SORT.DISABLE=false
MENU.REMOVE_MULTI.ENABLE=true
MENU.REMOVEALL.DISABLE=true
MENU.APN.DISABLE=true
USER.AGENT=Mozilla/5.0 (Linux; U; Android 2.3; en-us) Profile/MIDP-2.0 Configuration/CLDC-1.1
THEME=theme_memphis
BLOCKVM.AFTER.PHONE.HANGUP.ENABLE=true
LISTITEM.DATE.DISABLE=true
LISTITEM.SIZE.DISABLE=true
AMS.CONSTRAINT.NOTIFY=true
SEARCHFOLDER.EXCLUDE="/data/data/com.esmertec.android.jbed/LocalInstall:/mnt/sdcard/download"
AMS.CUSTOMICON.ENABLE=true
AMS.GENAPK=false
SOFT.KEYBOARD.SUPPORT=false
AMS.USING.SPECIAL.ICONS=false